version: '3'
services:
  fullstack-mysql:
    image: rizkyaddon/sqlsagara:v1
    container_name: sqlsagara
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=sagaracrud
      - MYSQL_ROOT_PASSWORD=password123secret
    networks:
      - fullstack    

  app:
    container_name: sagaracrud
    image : rizkyaddon/sagaracrud:v7
    ports: 
      - 4000:4000 
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    restart: always
    depends_on:
      - fullstack-mysql       
    networks:
      - fullstack

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
